# Generated by Django 6.0.5 on 2026-07-05 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], db_index=True, default='student', max_length=20, verbose_name='Member Role')),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Joined At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='courses.course', verbose_name='Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Course Member',
                'verbose_name_plural': 'Course Members',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['course', 'role'], name='member_course_role_idx'), models.Index(fields=['user', 'role'], name='member_user_role_idx'), models.Index(fields=['joined_at'], name='member_joined_idx')],
                'constraints': [models.UniqueConstraint(fields=('course', 'user'), name='unique_course_member')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Enrolled At')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['course', 'is_active'], name='enroll_course_active_idx'), models.Index(fields=['student', 'is_active'], name='enroll_student_active_idx'), models.Index(fields=['enrolled_at'], name='enroll_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('course', 'student'), name='unique_course_enrollment')],
            },
        ),
    ]
