# Generated by Django 6.0.5 on 2026-07-05 07:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Content Title')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Attachment')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='courses.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course Content',
                'verbose_name_plural': 'Course Contents',
                'ordering': ['course', 'order', 'id'],
                'indexes': [models.Index(fields=['course', 'order'], name='content_course_order_idx'), models.Index(fields=['created_at'], name='content_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('course', 'order'), name='unique_content_order_per_course')],
            },
        ),
    ]
