# Generated by Django 6.0.5 on 2026-07-05 07:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=180, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Course Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='course_thumbnails/', verbose_name='Thumbnail')),
                ('category', models.CharField(db_index=True, max_length=80, verbose_name='Category')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at', 'title'],
                'indexes': [models.Index(fields=['title'], name='course_title_idx'), models.Index(fields=['category', 'status'], name='course_category_status_idx'), models.Index(fields=['teacher', 'status'], name='course_teacher_status_idx'), models.Index(fields=['price'], name='course_price_idx'), models.Index(fields=['created_at'], name='course_created_idx')],
            },
        ),
    ]
